name: Test and Deploy pet-profile-service to Docker Hub

on:
  push:
    branches:
      - prod

env:
  IMAGE_NAME: pet-profile-service

jobs:
  test:
    runs-on: ubuntu-latest
    name: Simulated Unit Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run simulated test
        run: echo "No tests implemented yet" && exit 0

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Build and Push Docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
